#!/usr/bin/env php
<?php

/**
 * if we're running from phar load the phar autoload,
 * else let the script 'robo' search for the autoloader
 */
if (strpos(basename(__FILE__), 'phar')) {
    require_once 'phar://ci.phar/vendor/autoload.php';
} else {
    if (file_exists(__DIR__.'/vendor/autoload.php')) {
        require_once __DIR__.'/vendor/autoload.php';
    } elseif (file_exists(__DIR__.'/../../autoload.php')) {
        require_once __DIR__ . '/../../autoload.php';
    } else {
        require_once 'phar://robo.phar/vendor/autoload.php';
    }
}

$output = new \Symfony\Component\Console\Output\ConsoleOutput();

$commandClasses = [ \CI\Commands\TravisCommands::class ];
$statusCode = \Robo\Robo::run(
    $_SERVER['argv'],
    $commandClasses,
    'MyAppName',
    '0.1.0',
    $output,
    'consolidation/ci'
);
exit($statusCode);
